language: r
cache: packages
latex: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      service: mysql
      addons:
        apt:
          packages:
            - libmysqlclient-dev
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install mariadb
        - mysql.server start
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install mysql
        - mysql.server start
    - os: osx
      osx_image: xcode9.2
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'
    - os: osx
      osx_image: beta-xcode7.3
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - printf "[rs-dbi]\nusername=billy\npassword=supersecret\n" > ~/.my.cnf

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
